# Generated by Django 3.1.2 on 2020-11-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=10)),
                ('have_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotionRecognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('channel_number', models.IntegerField(default=0)),
                ('ready', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to='main.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to='main.player')),
            ],
        ),
    ]
